### ISSUE TITLE
Pass along the correct movement info in the update builder.

### ISSUE THREAD

**Issue by Victov** [Victov/wrath-rs#26]
In `update_builder.rs` there is [a TODO note](https://github.com/Victov/wrath-rs/blob/6cb4d45a34820e584f2800ff4e3e59fbb02dcc96/world_server/src/world/update_builder.rs#L23) about passing in the correct movement flags, which is currently blocked because they are different types and converting between them is not possible in a clean manner.

This task is blocked by [this issue](https://github.com/gtker/wow_messages/issues/31). When that task is done, bump the dependency on `wow_messages` and then update the code in `update_builder` to fix the todo.

**Comment by gtker** [comment]
https://github.com/Victov/wrath-rs/blob/6cb4d45a34820e584f2800ff4e3e59fbb02dcc96/world_server/src/world/update_builder.rs#L28 Can be replaced with 

```rust
let update_flag = movement_info.into_movement_block_update_flag_living(
    0.0, /* backwards_flight_speed */
    4.5, /* backwards_running_speed */
    0.0, /* backwards_swimming_speed */
    0.0, /* flight_speed */
    0.0, /* pitch_rate */
    7.0, /* running_speed */
    0.0, /* swimming_speed */
    std::f32::consts::PI, /* turn_rate */
    1.0, /* walking_speed */
    None, /* spline_enabled */
);
```

For `wow_messages` versions newer than commit `5e97728dfe68a907895f4cc7279d035fff2b8531`.
